export type SongSeed = {
  title: string;
  artist: string;
  year: number;
  spotifyId?: string;
};

export type Genre = 'international' | 'israeli';

export const ISRAELI_SONGS: SongSeed[] = [
  { title: "אני ואתה", artist: "Arik Einstein", year: 1971 },
  { title: "יושב על הגדר", artist: "Arik Einstein", year: 1982 },
  { title: "סע לאט", artist: "Arik Einstein", year: 1974 },
  { title: "ירח", artist: "Shlomo Artzi", year: 1992 },
  { title: "האהבה הישנה", artist: "Shlomo Artzi", year: 1996 },
  { title: "רוב הזמן את אישתי", artist: "Shlomo Artzi", year: 1984 },
  { title: "הפרח בגני", artist: "Zohar Argov", year: 1982 },
  { title: "נכון להיום", artist: "Zohar Argov", year: 1982 },
  { title: "כשהלב בוכה", artist: "Sarit Hadad", year: 2001 },
  { title: "בחום של תל אביב", artist: "Sarit Hadad", year: 2004 },
  { title: "מרוץ החיים", artist: "Sarit Hadad", year: 2009 },
  { title: "גומיגם", artist: "Static & Ben El Tavori", year: 2018 },
  { title: "בננות", artist: "Static & Ben El Tavori", year: 2019 },
  { title: "Kvish Hachof", artist: "Static & Ben El Tavori", year: 2016 },
  { title: "ממעמקים", artist: "The Idan Raichel Project", year: 2005 },
  { title: "בואי", artist: "The Idan Raichel Project", year: 2002 },
  { title: "ואם תבואי אליי", artist: "The Idan Raichel Project", year: 2018 },
  { title: "מלכת הדור", artist: "Omer Adam", year: 2015 },
  { title: "טיסה 5325", artist: "Moshe Peretz", year: 2016 },
  { title: "אלייך", artist: "Moshe Peretz", year: 2008 },
  { title: "היא לא תשוב", artist: "Ethnix", year: 1996 },
  { title: "שיר ישן", artist: "Ethnix", year: 1991 },
  { title: "מחר", artist: "Aviv Geffen", year: 2006 },
  { title: "סוף העולם", artist: "Aviv Geffen", year: 1997 },
  { title: "היא התווכחה איתו שעות", artist: "Mashina", year: 1986 },
  { title: "רכבת לילה לקהיר", artist: "Mashina", year: 1985 },
  { title: "שיר המכולת", artist: "Kaveret", year: 1973 },
  { title: "מדינה קטנה", artist: "Kaveret", year: 1975 },
  { title: "היא כל כך יפה", artist: "Kaveret", year: 1975 },
  { title: "אמצע הלילה בכפר", artist: "Harel Moyal", year: 2005 },
  { title: "יד ביד", artist: "Ofra Haza", year: 1983 },
  { title: "Diva (Hebrew Version)", artist: "Dana International", year: 1998 },
  { title: "TOY (Eurovision 2018 - Israel)", artist: "Netta", year: 2018 },
  { title: "Unicorn", artist: "Noa Kirel", year: 2023 },
  { title: "שירת הסטיקר", artist: "Hadag Nahash", year: 2004 },
  { title: "Shir Nechama", artist: "Hadag Nahash", year: 2010 },
  { title: "זמן להתעורר", artist: "Hadag Nahash", year: 2013 },
  { title: "הכי ישראלי", artist: "Hatikva 6", year: 2015 },
  { title: "עוד פעם פעם", artist: "Hatikva 6", year: 2014 },
  { title: "לחזור הביתה", artist: "Hatikva 6", year: 2020 },
  { title: "מבול", artist: "Keren Peles", year: 2008 },
  { title: "באת לי פתאום", artist: "Keren Peles", year: 2019 },
  { title: "אתמול היית שונה", artist: "Shimi Tavori", year: 1980 },
  { title: "בך לא נוגע", artist: "Yehudit Ravitz", year: 2000 },
  { title: "באה מאהבה", artist: "Yehudit Ravitz", year: 1987 },
  { title: "מה עושות האילות", artist: "Yehudit Ravitz", year: 1979 },
  { title: "אנטארקטיקה", artist: "Corinne Allal", year: 1989 },
  { title: "כשזה עמוק", artist: "Corinne Allal", year: 1997 },
  { title: "זן נדיר", artist: "Corinne Allal", year: 1992 },
  { title: "נופל וקם", artist: "Shabak Samech", year: 2000 },
  { title: "עד מחר", artist: "Eviatar Banai", year: 2009 },
  { title: "תיאטרון רוסי", artist: "Eviatar Banai", year: 1997 },
  { title: "רוחות הצפון", artist: "Ehud Banai", year: 1989 },
  { title: "בלוז כנעני", artist: "Ehud Banai", year: 2004 },
  { title: "כולם יודעים", artist: "Ehud Banai", year: 1989 },
  { title: "הלוואי", artist: "Boaz Sharabi", year: 1986 },
  { title: "חופשי ומאושר", artist: "Boaz Sharabi", year: 1989 },
  { title: "אם את עדיין אוהבת אותי", artist: "Boaz Sharabi", year: 2006 },
  { title: "הימים עוברים", artist: "Avraham Tal", year: 2015 },
  { title: "שבוע טוב", artist: "Avraham Tal", year: 2020 },
  { title: "אדם בתוך עצמו", artist: "Shalom Hanoch", year: 1977 },
  { title: "אהבת נעורי", artist: "Shalom Hanoch", year: 2003 },
  { title: "מחכים למשיח", artist: "Shalom Hanoch", year: 1985 },
  { title: "מונסון", artist: "Berry Sakharof", year: 2001 },
  { title: "חלליות", artist: "Berry Sakharof", year: 1991 },
  { title: "מה שאת אוהבת", artist: "Gali Atari", year: 2003 },
  { title: "חזקה מהרוח", artist: "Gali Atari", year: 1992 },
  { title: "ציפור קטנה בלב", artist: "Yigal Bashan", year: 1975 },
  { title: "סיון", artist: "Yigal Bashan", year: 1981 },
  { title: "קפה אצל ברטה", artist: "Yigal Bashan", year: 1974 },
  { title: "גם זה יעבור", artist: "Tuna", year: 2015 },
  { title: "עולם משוגע", artist: "Tuna", year: 2016 },
  { title: "רוני", artist: "Gazoz", year: 1979 },
  { title: "מילים יפות", artist: "Gazoz", year: 1979 },
  { title: "אני בא הביתה מהלילה", artist: "Danny Robas", year: 1983 },
  { title: "בדרך אל האושר", artist: "Danny Robas", year: 1989 },
  { title: "אני לא מפסיק להתרגש ממך", artist: "Danny Robas", year: 2013 },
  { title: "יום שישי", artist: "Benzin", year: 1982 },
  { title: "חפשי זה לגמרי לבד", artist: "Benzin", year: 1982 },
  { title: "לא יכול להוריד ממך את העיניים", artist: "Meir Ariel", year: 1997 },
  { title: "טרמינל לומינלט", artist: "Meir Ariel", year: 1979 },
  { title: "להשתטות לפעמים", artist: "Gabi Shoshan", year: 1974 },
  { title: "שש עשרה מלאו לנער", artist: "Gabi Shoshan", year: 1973 },
  { title: "הבלדה למחלקה להלבשה תחתונה", artist: "Mercedes Band", year: 2009 },
  { title: "בואי ונביא לך ת'פאנק", artist: "Mercedes Band", year: 2004 },
];

export const INTERNATIONAL_SONGS: SongSeed[] = [
  { title: "Sunny", artist: "Boney M.", year: 1976, spotifyId: "3pf96IFggfQuT6Gafqx2rt" },
  { title: "It's Raining Men", artist: "The Weather Girls", year: 1982, spotifyId: "2IvetNzSZMH5gwjInoyr18" },
  { title: "Speedy Gonzales", artist: "Pat Boone", year: 1962, spotifyId: "3TmnUIbelFiDzrhZqavHU0" },
  { title: "Stressed Out", artist: "Twenty One Pilots", year: 2015, spotifyId: "3CRDbSIZ4r5MsZ0YwxuEkn" },
  { title: "Baby Got Back", artist: "Sir Mix-A-Lot", year: 1992, spotifyId: "1SAkL1mYNJlaqnBQxVZrRl" },
  { title: "Would I Lie To You?", artist: "Charles & Eddie", year: 1992, spotifyId: "3PkvYP6223QO3xlW2THd1x" },
  { title: "If You Leave Me Now", artist: "Chicago", year: 1976, spotifyId: "0KMGxYKeUzK9wc5DZCt3HT" },
  { title: "Holding Out for a Hero", artist: "Bonnie Tyler", year: 1984, spotifyId: "5Hyr47BBGpvOfcykSCcaw9" },
  { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: 1983, spotifyId: "4y1LsJpmMti1PfRQV9AWWe" },
  { title: "What Is Love", artist: "Haddaway", year: 1993, spotifyId: "7JkZ2hQdDonRURJjlMuh8q" },
  { title: "Viva La Vida", artist: "Coldplay", year: 2008, spotifyId: "1mea3bSkSGXuIRvnydlB5b" },
  { title: "Karma Chameleon", artist: "Culture Club", year: 1983, spotifyId: "3XDeeP9wBZzGhIPZmLfEEx" },
  { title: "Free Fallin'", artist: "Tom Petty", year: 1989, spotifyId: "5tVA6TkbaAH9QMITTQRrNv" },
  { title: "Happier", artist: "Marshmello", year: 2018, spotifyId: "7BqHUALzNBTanL6OvsqmC1" },
  { title: "Will You Still Love Me Tomorrow", artist: "The Shirelles", year: 1961, spotifyId: "33AeObqTI5RW6IhHmIyxVT" },
  { title: "I Like It", artist: "Cardi B", year: 2018, spotifyId: "58q2HKrzhC3ozto2nDdN4z" },
  { title: "Where Did Our Love Go", artist: "The Supremes", year: 1964, spotifyId: "69RH84na5iUNwrwxpgjC5j" },
  { title: "Counting Stars", artist: "OneRepublic", year: 2013, spotifyId: "2tpWsVSb9UEmDRxAl1zhX1" },
  { title: "Lemon Tree", artist: "Fools Garden", year: 1995, spotifyId: "2epbL7s3RFV81K5UhTgZje" },
  { title: "Torn", artist: "Natalie Imbruglia", year: 1997, spotifyId: "1Jaah2tmN9Hv81A87KZ1MU" },
  { title: "Shape of You", artist: "Ed Sheeran", year: 2017, spotifyId: "7qiZfU4dY1lWllzX7mPBI3" },
  { title: "Waka Waka", artist: "Shakira", year: 2010, spotifyId: "63Tl9k1sH8tznn3bqoMuyF" },
  { title: "Killing Me Softly With His Song", artist: "Roberta Flack", year: 1973, spotifyId: "3gsCAGsWr6pUm1Vy7CPPob" },
  { title: "Three Little Birds", artist: "Bob Marley & The Wailers", year: 1977, spotifyId: "7vggqxNKwd6xdRoYS0pQtM" },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: 1987, spotifyId: "2tUBqZG2AbRi7Q0BIrVrEj" },
  { title: "Funkytown", artist: "Lipps Inc.", year: 1980, spotifyId: "2XVQdI3m0giGxNrwUhV3yP" },
  { title: "Broken Wings", artist: "Mr. Mister", year: 1985, spotifyId: "78FHUZRbFDCG6VkRAQdFLm" },
  { title: "Cotton Eye Joe", artist: "Rednex", year: 1994, spotifyId: "06hsdMbBxWGqBO0TV0Zrkf" },
  { title: "Don't Worry Be Happy", artist: "Bobby McFerrin", year: 1988, spotifyId: "5YbgcwHjQhdT1BYQ4rxWlD" },
  { title: "Don't You Want Me", artist: "The Human League", year: 1981, spotifyId: "3L7RtEcu1Hw3OXrpnthngx" },
  { title: "Can't Take My Eyes off You", artist: "Frankie Valli", year: 1967, spotifyId: "6ft9PAgNOjmZ2kFVP7LGqb" },
  { title: "Umbrella", artist: "Rihanna", year: 2007, spotifyId: "49FYlytm3dAAraYgpoJZux" },
  { title: "I Want It That Way", artist: "Backstreet Boys", year: 1999, spotifyId: "47BBI51FKFwOMlIiX6m8ya" },
  { title: "With Or Without You", artist: "U2", year: 1987, spotifyId: "6ADSaE87h8Y3lccZlBJdXH" },
  { title: "Dance Monkey", artist: "Tones And I", year: 2019, spotifyId: "2XU0oxnq2qxCpomAAuJY8K" },
  { title: "Girl on Fire", artist: "Alicia Keys", year: 2012, spotifyId: "4esOae7i4rqTbAu9o5Pxco" },
  { title: "YMCA", artist: "Village People", year: 1978, spotifyId: "3PR0Y4RokWNXUOxg7qQPi1" },
  { title: "Son Of A Preacher Man", artist: "Dusty Springfield", year: 1968, spotifyId: "6ek9SiEj5a65WIs2EV7qiM" },
  { title: "Put Your Records On", artist: "Corinne Bailey Rae", year: 2006, spotifyId: "2nGFzvICaeEWjIrBrL2RAx" },
  { title: "Lovefool", artist: "The Cardigans", year: 1996, spotifyId: "7aQjPecQdIuNd1sz3KCDhD" },
  { title: "7 Years", artist: "Lukas Graham", year: 2015, spotifyId: "5kqIPrATaCc2LqxVWzQGbk" },
  { title: "Take Me Home Country Roads", artist: "John Denver", year: 1971, spotifyId: "1YYhDizHx7PnDhAhko6cDS" },
  { title: "I'm a Believer", artist: "The Monkees", year: 1966, spotifyId: "3G7tRC24Uh09Hmp1KZ7LQ2" },
  { title: "What Makes You Beautiful", artist: "One Direction", year: 2011, spotifyId: "4cluDES4hQEUhmXj6TXkSo" },
  { title: "Who Let The Dogs Out", artist: "Baha Men", year: 2000, spotifyId: "1H5tvpoApNDxvxDexoaAUo" },
  { title: "Losing My Religion", artist: "R.E.M.", year: 1991, spotifyId: "31AOj9sFz2gM0O3hMARRBx" },
  { title: "Genie In a Bottle", artist: "Christina Aguilera", year: 1999, spotifyId: "11mwFrKvLXCbcVGNxffGyP" },
  { title: "We Are Family", artist: "Sister Sledge", year: 1979, spotifyId: "5IKLwqBQG6KU6MP2zP80Nu" },
  { title: "I Love It", artist: "Icona Pop", year: 2012, spotifyId: "2U8NXPTXZWG2O0ye2sYRiH" },
  { title: "Royals", artist: "Lorde", year: 2013, spotifyId: "4MsiLAu9vLksjyTx6WSVCn" },
  { title: "Another Brick in the Wall Pt. 2", artist: "Pink Floyd", year: 1979, spotifyId: "4gMgiXfqyzZLMhsksGmbQV" },
  { title: "Can't Help Falling in Love", artist: "Elvis Presley", year: 1961, spotifyId: "44AyOl4qVkzS48vBsbNXaC" },
  { title: "Flashdance What a Feeling", artist: "Irene Cara", year: 1983, spotifyId: "3cbV252akVZInSvJk7jAYX" },
  { title: "Smoke on the Water", artist: "Deep Purple", year: 1972, spotifyId: "5MMnwYs0hIxkENRsbkWJ2G" },
  { title: "Hips Don't Lie", artist: "Shakira", year: 2005, spotifyId: "3d0WouFnFmr0K3kjeza3fF" },
  { title: "Poker Face", artist: "Lady Gaga", year: 2008, spotifyId: "1QV6tiMFM6fSOKOGLMHYYg" },
  { title: "Wannabe", artist: "Spice Girls", year: 1996, spotifyId: "1Je1IMUlBXcx1Fz0WE7oPT" },
  { title: "Closer", artist: "The Chainsmokers", year: 2016, spotifyId: "7BKLCZ1jbUBVqRi2FVlTVw" },
  { title: "Eye of the Tiger", artist: "Survivor", year: 1982, spotifyId: "2KH16WveTQWT6KOG9Rg6e2" },
  { title: "Rhythm Is a Dancer", artist: "SNAP!", year: 1992, spotifyId: "5uFYYOyT3EclOVhiFzPJSz" },
  { title: "In the Summertime", artist: "Mungo Jerry", year: 1970, spotifyId: "2uzlv8PjqsVvF1DhEahyhy" },
  { title: "We Don't Talk Anymore", artist: "Charlie Puth", year: 2016, spotifyId: "06KyNuuMOX1ROXRhj787tj" },
  { title: "Kiss Me", artist: "Sixpence None The Richer", year: 1997, spotifyId: "754kgU5rWscRTfvlsuEwFp" },
  { title: "I Heard It Through The Grapevine", artist: "Marvin Gaye", year: 1968, spotifyId: "1tqT6DhmsrtQgyCKUwotiw" },
  { title: "Baby", artist: "Justin Bieber", year: 2010, spotifyId: "6epn3r7S14KUqlReYr77hA" },
  { title: "Forever Young", artist: "Alphaville", year: 1984, spotifyId: "4S1VYqwfkLit9mKVY3MXoo" },
  { title: "Hollaback Girl", artist: "Gwen Stefani", year: 2004, spotifyId: "0eqH0ALoDQevq59YcQ53KE" },
  { title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1992, spotifyId: "3d9DChrdc6BOeFsbrZ3Is0" },
  { title: "La Bamba", artist: "Ritchie Valens", year: 1958, spotifyId: "6nMzaWZFYKXo2O6OqbfBnO" },
  { title: "Gimme! Gimme! Gimme!", artist: "ABBA", year: 1979, spotifyId: "3vkQ5DAB1qQMYO4Mr9zJN6" },
  { title: "Believe", artist: "Cher", year: 1998, spotifyId: "2goLsvvODILDzeeiT4dAoR" },
  { title: "Easy", artist: "Commodores", year: 1977, spotifyId: "1JQ6Xm1JrvHfvAqhl5pwaA" },
  { title: "The Final Countdown", artist: "Europe", year: 1986, spotifyId: "3MrRksHupTVEQ7YbA0FsZK" },
  { title: "Dream Lover", artist: "Bobby Darin", year: 1959, spotifyId: "1KLpjQFgubHI3GkAICCNH3" },
  { title: "These Boots Are Made for Walkin'", artist: "Nancy Sinatra", year: 1966, spotifyId: "2PneNdtypG6XcgmWmGd9FI" },
  { title: "Treat You Better", artist: "Shawn Mendes", year: 2016, spotifyId: "3QGsuHI8jO1Rx4JWLUh9jd" },
  { title: "Lollipop", artist: "The Chordettes", year: 1958, spotifyId: "3VjFR6D9ayHB1tMsvsM8tQ" },
  { title: "Twist And Shout", artist: "The Isley Brothers", year: 1962, spotifyId: "7iFdUmdqT9XrsJdSGf9KrX" },
  { title: "This Is The Life", artist: "Amy Macdonald", year: 2007, spotifyId: "2T3jgoAMbBXiMMD8pSc6QL" },
  { title: "Somebody That I Used to Know", artist: "Gotye", year: 2011, spotifyId: "1qDrWA6lyx8cLECdZE7TV7" },
  { title: "My Girl", artist: "The Temptations", year: 1965, spotifyId: "745H5CctFr12Mo7cqa1BMH" },
  { title: "Set Fire to the Rain", artist: "Adele", year: 2011, spotifyId: "3di5hcvxxciiqwMH1jarhY" },
  { title: "Your Song", artist: "Elton John", year: 1970, spotifyId: "38zsOOcu31XbbYj9BIPUF1" },
  { title: "Scream & Shout", artist: "will.i.am", year: 2012, spotifyId: "2iJuuzV8P9Yz0VSurttIV5" },
  { title: "Big Girls Don't Cry", artist: "Frankie Valli & The Four Seasons", year: 1962, spotifyId: "00meczE1jpLTX0BBzIGrAR" },
  { title: "You Spin Me Round", artist: "Dead Or Alive", year: 1985, spotifyId: "1ChulFMnwxoD74Me8eX2TU" },
  { title: "Clint Eastwood", artist: "Gorillaz", year: 2001, spotifyId: "1RKUoGiLEbcXN4GY4spQDx" },
  { title: "American Pie", artist: "Don McLean", year: 1971, spotifyId: "1fDsrQ23eTAVFElUMaf38X" },
  { title: "Never Gonna Give You Up", artist: "Rick Astley", year: 1987, spotifyId: "4PTG3Z6ehGkBFwjybzWkR8" },
  { title: "Low", artist: "Flo Rida", year: 2007, spotifyId: "0CAfXk7DXMnon4gLudAp7J" },
  { title: "Rehab", artist: "Amy Winehouse", year: 2006, spotifyId: "1L5tZi0izXsi5Kk5OJf4W0" },
  { title: "U Can't Touch This", artist: "MC Hammer", year: 1990, spotifyId: "1B75hgRqe7A4fwee3g3Wmu" },
  { title: "Bitter Sweet Symphony", artist: "The Verve", year: 1997, spotifyId: "57iDDD9N9tTWe75x6qhStw" },
  { title: "Africa", artist: "TOTO", year: 1982, spotifyId: "2374M0fQpWi3dLnB54qaLX" },
  { title: "As It Was", artist: "Harry Styles", year: 2022, spotifyId: "4Dvkj6JhhA12EX05fT7y2e" },
  { title: "Enjoy the Silence", artist: "Depeche Mode", year: 1990, spotifyId: "6WK9dVrRABMkUXFLNlgWFh" },
  { title: "Material Girl", artist: "Madonna", year: 1984, spotifyId: "7bkyXSi4GtVfD7itZRUR3e" },
  { title: "Say My Name", artist: "Destiny's Child", year: 1999, spotifyId: "7H6ev70Weq6DdpZyyTmUXk" },
  { title: "Murder On The Dancefloor", artist: "Sophie Ellis-Bextor", year: 2001, spotifyId: "4tKGFmENO69tZR9ahgZu48" },
  { title: "Rock Around The Clock", artist: "Bill Haley & His Comets", year: 1955, spotifyId: "34AmZ4PMz9iNZVp9AMIGZj" },
  { title: "The Real Slim Shady", artist: "Eminem", year: 2000, spotifyId: "3yfqSUWxFvZELEM4PmlwIR" },
  { title: "Flowers", artist: "Miley Cyrus", year: 2023, spotifyId: "7DSAEUvxU8FajXtRloy8M0" },
  { title: "The Ketchup Song", artist: "Las Ketchup", year: 2002, spotifyId: "6UEfyhyfhYQsyipxOd95Ie" },
  { title: "Crazy In Love", artist: "Beyoncé", year: 2003, spotifyId: "5IVuqXILoxVWvWEPm82Jxr" },
  { title: "Gonna Fly Now", artist: "Bill Conti", year: 1976, spotifyId: "7iXYRR70wewzVYzWScm99j" },
  { title: "Stayin' Alive", artist: "Bee Gees", year: 1977, spotifyId: "5ubvP9oKmxLUVq506fgLhk" },
  { title: "No Scrubs", artist: "TLC", year: 1999, spotifyId: "1KGi9sZVMeszgZOWivFpxs" },
  { title: "Jolene", artist: "Dolly Parton", year: 1973, spotifyId: "2SpEHTbUuebeLkgs9QB7Ue" },
  { title: "Have You Ever Seen The Rain", artist: "Creedence Clearwater Revival", year: 1970, spotifyId: "2LawezPeZhN4AWuSB0GtAU" },
  { title: "Everybody Wants To Rule The World", artist: "Tears For Fears", year: 1985, spotifyId: "4RvWPyQ5RL0ao9LPZeSouE" },
  { title: "Ain't Nobody", artist: "Rufus", year: 1983, spotifyId: "53Za5vyGc1x7GxgJVRjRKc" },
  { title: "San Francisco", artist: "Scott McKenzie", year: 1967, spotifyId: "6vcNJUWtUPB0hKC6VbZriY" },
  { title: "Price Tag", artist: "Jessie J", year: 2011, spotifyId: "2fTsFCKRFQ5M0igJgabnLA" },
  { title: "Ice Ice Baby", artist: "Vanilla Ice", year: 1990, spotifyId: "11d9oUiwHuYt216EFA2tiz" },
  { title: "My Heart Will Go On", artist: "Céline Dion", year: 1997, spotifyId: "33LC84JgLvK2KuW43MfaNq" },
  { title: "Happy", artist: "Pharrell Williams", year: 2013, spotifyId: "60nZcImufyMA1MKQY3dcCH" },
  { title: "Hangover", artist: "Taio Cruz", year: 2011, spotifyId: "5pmL3RzOy3IvGFaSDi4hZL" },
  { title: "Lambada", artist: "Kaoma", year: 1989, spotifyId: "6xepovPqjvrkEw9Y5AMmTm" },
  { title: "Hotel California", artist: "Eagles", year: 1977, spotifyId: "40riOy7x9W7GXjyGp4pjAv" },
  { title: "Payphone", artist: "Maroon 5", year: 2012, spotifyId: "1XGmzt0PVuFgQYYnV2It7A" },
  { title: "Come and Get Your Love", artist: "Redbone", year: 1974, spotifyId: "7GVUmCP00eSsqc4tzj1sDD" },
  { title: "All Star", artist: "Smash Mouth", year: 1999, spotifyId: "3cfOd4CMv2snFaKAnMdnvK" },
  { title: "Lean On", artist: "Major Lazer", year: 2015, spotifyId: "01aTsQoKoeXofSTvKuunzv" },
  { title: "Get Lucky", artist: "Daft Punk", year: 2013, spotifyId: "69kOkLUCkxIZYexIgSG8rq" },
  { title: "The Boy Is Mine", artist: "Brandy", year: 1998, spotifyId: "6sHsXIJoEN5JpdkGMQDJxt" },
  { title: "Cheap Thrills", artist: "Sia", year: 2016, spotifyId: "378iszndTZAR4dH8kwsLC6" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991, spotifyId: "4CeeEOM32jQcH3eN9Q2dGj" },
  { title: "Valerie", artist: "Mark Ronson", year: 2007, spotifyId: "6kopmMZiyLmw7h66uXcXR7" },
  { title: "Clocks", artist: "Coldplay", year: 2002, spotifyId: "0BCPKOYdS2jbQ8iyB56Zns" },
  { title: "Sweet Caroline", artist: "Neil Diamond", year: 1969, spotifyId: "62AuGbAkt8Ox2IrFFb8GKV" },
  { title: "California Dreamin'", artist: "The Mamas & The Papas", year: 1965, spotifyId: "1ZEOIhSn6BKErV59bIgn76" },
  { title: "Save Tonight", artist: "Eagle-Eye Cherry", year: 1998, spotifyId: "0smyCrJiibi2uwCiq5R1vj" },
  { title: "All About That Bass", artist: "Meghan Trainor", year: 2014, spotifyId: "5jE48hhRu8E6zBDPRSkEq7" },
  { title: "CAN'T STOP THE FEELING!", artist: "Justin Timberlake", year: 2016, spotifyId: "6JV2JOEocMgcZxYSZelKcc" },
  { title: "Riptide", artist: "Vance Joy", year: 2013, spotifyId: "7yq4Qj7cqayVTp3FF9CWbm" },
  { title: "Sweet Dreams", artist: "Eurythmics", year: 1983, spotifyId: "1TfqLAPs4K3s2rJMoCokcS" },
  { title: "Stand By Me", artist: "Ben E. King", year: 1961, spotifyId: "3SdTKo2uVsxFblQjpScoHy" },
  { title: "Barbie Girl", artist: "Aqua", year: 1997, spotifyId: "5ZrDlcxIDZyjOzHdYW1ydr" },
  { title: "Self Control", artist: "Laura Branigan", year: 1984, spotifyId: "6JNJERZGJwDVgkmbohBw7u" },
  { title: "Believer", artist: "Imagine Dragons", year: 2017, spotifyId: "0pqnGHJpmpxLKifKRmU6WP" },
  { title: "Sweet Child O'Mine", artist: "Guns N'Roses", year: 1987, spotifyId: "7snQQk1zcKl8gZ92AnueZW" },
  { title: "Running Up That Hill", artist: "Kate Bush", year: 1985, spotifyId: "1PtQJZVZIdWIYdARpZRDFO" },
  { title: "Be My Baby", artist: "The Ronettes", year: 1963, spotifyId: "2G2YzndIA6jeWFPBXhUjh5" },
  { title: "Iris", artist: "The Goo Goo Dolls", year: 1998, spotifyId: "6Qyc6fS4DsZjB2mRW9DsQs" },
  { title: "Tequila", artist: "The Champs", year: 1958, spotifyId: "5gJKsGij5oGt5H5RSFYXPa" },
  { title: "Wonderwall", artist: "Oasis", year: 1995, spotifyId: "5qqabIl2vWzo9ApSC317sa" },
  { title: "Sing Hallelujah!", artist: "Dr. Alban", year: 1992, spotifyId: "2qjDNbgLzfBpCvDwfw11Qg" },
  { title: "Oops!...I Did It Again", artist: "Britney Spears", year: 2000, spotifyId: "6naxalmIoLFWR0siv8dnQQ" },
  { title: "I Gotta Feeling", artist: "Black Eyed Peas", year: 2009, spotifyId: "4kLLWz7srcuLKA7Et40PQR" },
  { title: "Dragostea din tei", artist: "O-Zone", year: 2003, spotifyId: "52Zr0sinhWTCRrQhRRY4EP" },
  { title: "You Give Love A Bad Name", artist: "Bon Jovi", year: 1986, spotifyId: "0rmGAIH9LNJewFw7nKzZnc" },
  { title: "You Can Call Me Al", artist: "Paul Simon", year: 1986, spotifyId: "0qxYx4F3vm1AOnfux6dDxP" },
  { title: "Bohemian Rhapsody", artist: "Queen", year: 1975, spotifyId: "3z8h0TU7ReDPLIbEnYhWZb" },
  { title: "Careless Whisper", artist: "George Michael", year: 1984, spotifyId: "5WDLRQ3VCdVrKw0njWe5E5" },
  { title: "The Lazy Song", artist: "Bruno Mars", year: 2010, spotifyId: "386RUes7n1uM1yfzgeUuwp" },
  { title: "The House of the Rising Sun", artist: "The Animals", year: 1964, spotifyId: "4mn2kNTqiGLwaUR8JdhJ1l" },
  { title: "Zombie", artist: "The Cranberries", year: 1994, spotifyId: "49wOjOkS4pBK3PQnPnNYjb" },
  { title: "Dilemma", artist: "Nelly", year: 2002, spotifyId: "0ARK753YaiJbpLUk7z5yIM" },
  { title: "I Got You", artist: "James Brown & The Famous Flames", year: 1965, spotifyId: "5haXbSJqjjM0TCJ5XkfEaC" },
  { title: "Build Me Up Buttercup", artist: "The Foundations", year: 1968, spotifyId: "1tfZtA15BfJHQTUy3dqTKC" },
  { title: "Shake It Off", artist: "Taylor Swift", year: 2014, spotifyId: "0cqRj7pUJDkTCEsJkx8snD" },
  { title: "It's My Party", artist: "Lesley Gore", year: 1963, spotifyId: "1Pq47iFLC5U7j8xeNiNcuS" },
  { title: "Happy Birthday", artist: "Stevie Wonder", year: 1980, spotifyId: "5fBlnN4KvXlH1T5CmNE5Sm" },
  { title: "Feel", artist: "Robbie Williams", year: 2002, spotifyId: "2Ms33RTRCT6gArrpcrPxmo" },
  { title: "Celebration", artist: "Kool & The Gang", year: 1980, spotifyId: "3K7Q9PHUWPTaknlbFPThn2" },
  { title: "Starships", artist: "Nicki Minaj", year: 2012, spotifyId: "2EBCVPNAG46nbgs6jXPGvv" },
  { title: "Piano Man", artist: "Billy Joel", year: 1973, spotifyId: "70C4NyhjD5OZUMzvWZ3njJ" },
  { title: "Oh Pretty Woman", artist: "Roy Orbison", year: 1964, spotifyId: "48i055G1OT5KxGGftwFxWy" },
  { title: "Fireflies", artist: "Owl City", year: 2009, spotifyId: "3DamFFqW32WihKkTVlwTYQ" },
  { title: "I'm So Excited", artist: "The Pointer Sisters", year: 1982, spotifyId: "1ot6jEe4w4hYnsOPjd3xKQ" },
  { title: "Yeah!", artist: "USHER", year: 2004, spotifyId: "5rb9QrpfcKFHM1EUbSIurX" },
  { title: "Jailhouse Rock", artist: "Elvis Presley", year: 1957, spotifyId: "4gphxUgq0JSFv2BCLhNDiE" },
  { title: "Mercy", artist: "Duffy", year: 2008, spotifyId: "1zusIxNqJu8i4g6P6hJ2Qa" },
  { title: "Surfin' U.S.A.", artist: "The Beach Boys", year: 1963, spotifyId: "2EPr9Wx7e1cpGEbNAtuN7x" },
  { title: "The Time of My Life", artist: "Bill Medley", year: 1987, spotifyId: "6W7ztLBiRzBN46ZaPAcQ0F" },
  { title: "In Da Club", artist: "50 Cent", year: 2003, spotifyId: "7iL6o9tox1zgHpKUfh9vuC" },
  { title: "Conga!", artist: "Miami Sound Machine", year: 1985, spotifyId: "3FdHgoJbH3DXNtGLh56pFu" },
  { title: "good 4 u", artist: "Olivia Rodrigo", year: 2021, spotifyId: "4ZtFanR9U6ndgddUvNcjcG" },
  { title: "Happy Together", artist: "The Turtles", year: 1967, spotifyId: "1JO1xLtVc8mWhIoE3YaCL0" },
  { title: "Gangsta's Paradise", artist: "Coolio", year: 1995, spotifyId: "1DIXPcTDzTj8ZMHt3PDt8p" },
  { title: "Taki Taki", artist: "DJ Snake", year: 2018, spotifyId: "20uYAdCEoIkSZStIfPW1TB" },
  { title: "Maneater", artist: "Daryl Hall & John Oates", year: 1982, spotifyId: "7j74lucZ59vqN67Ipe2ZcY" },
  { title: "Sugar Sugar", artist: "The Archies", year: 1969, spotifyId: "3iSws76HjaU7k49EqJVTfF" },
  { title: "Johnny B. Goode", artist: "Chuck Berry", year: 1958, spotifyId: "2QfiRTz5Yc8DdShCxG1tB2" },
  { title: "I'll Be There for You", artist: "The Rembrandts", year: 1995, spotifyId: "15tHagkk8z306XkyOHqiip" },
  { title: "Can't Get You out of My Head", artist: "Kylie Minogue", year: 2001, spotifyId: "3E7ZwUMJFqpsDOJzEkBrQ7" },
  { title: "Unwritten", artist: "Natasha Bedingfield", year: 2004, spotifyId: "3U5JVgI2x4rDyHGObzJfNf" },
  { title: "Ghostbusters", artist: "Ray Parker Jr.", year: 1984, spotifyId: "3m0y8qLoznUYi73SUBP8GI" },
  { title: "positions", artist: "Ariana Grande", year: 2020, spotifyId: "35mvY5S1H3J2QZyna3TFe0" },
  { title: "Mr. Tambourine Man", artist: "The Byrds", year: 1965, spotifyId: "2HCaIYjkvWSZzaSKUoOh3d" },
  { title: "Beggin'", artist: "The Four Seasons", year: 1967, spotifyId: "2S6XOQqWqUBIySUU00vMru" },
  { title: "Rocket Man", artist: "Elton John", year: 1972, spotifyId: "3gdewACMIVMEWVbyb8O9sY" },
  { title: "Here Comes The Sun", artist: "The Beatles", year: 1969, spotifyId: "6dGnYIeXmHdcikdzNNDMm2" },
  { title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd", year: 1974, spotifyId: "7e89621JPkKaeDSTQ3avtg" },
  { title: "No Woman No Cry", artist: "Bob Marley & The Wailers", year: 1974, spotifyId: "3PQLYVskjUeRmRIfECsL0X" },
  { title: "Unicorn", artist: "Noa Kirel", year: 2023, spotifyId: "6dUregFbvUNqHP5nphqesK" },
  { title: "Despacito", artist: "Luis Fonsi", year: 2017, spotifyId: "6habFhsOp2NvshLv26DqMb" },
  { title: "All of Me", artist: "John Legend", year: 2013, spotifyId: "3U4isOIWM3VvDubwSI3y7a" },
  { title: "Heart Of Glass", artist: "Blondie", year: 1979, spotifyId: "41AE8ODX2JETBCa6muhSLY" },
  { title: "Firework", artist: "Katy Perry", year: 2010, spotifyId: "1mXuMM6zjPgjL4asbBsgnt" },
  { title: "The Rhythm of the Night", artist: "Corona", year: 1994, spotifyId: "5UCPOJs8VJARoIX6acKRuJ" },
  { title: "Roxanne", artist: "The Police", year: 1978, spotifyId: "3EYOJ48Et32uATr9ZmLnAo" },
  { title: "Blinding Lights", artist: "The Weeknd", year: 2019, spotifyId: "0VjIjW4GlUZAMYd2vXMi3b" },
  { title: "Watermelon Sugar", artist: "Harry Styles", year: 2019, spotifyId: "6UelLqGlWMcVH1E5c4H7lY" },
  { title: "Call Me Maybe", artist: "Carly Rae Jepsen", year: 2012, spotifyId: "20I6sIOMTCkB6w7ryavxtO" },
  { title: "Take Me To Church", artist: "Hozier", year: 2013, spotifyId: "3dYD57lRAUcMHufyqn9GcI" },
  { title: "You Don't Own Me", artist: "Lesley Gore", year: 1963, spotifyId: "7ngRS53kqxLcEt9Pythc5d" },
  { title: "Hey Soul Sister", artist: "Train", year: 2009, spotifyId: "4HlFJV71xXKIGcU3kRyttv" },
  { title: "Let It Be", artist: "The Beatles", year: 1970, spotifyId: "7iN1s7xHE4ifF5povM6A48" },
  { title: "We Are The Champions", artist: "Queen", year: 1977, spotifyId: "1lCRw5FEZ1gPDNPzy1K4zW" },
  { title: "Hey Ya!", artist: "Outkast", year: 2003, spotifyId: "2PpruBYCo4H7WOBJ7Q2EwM" },
  { title: "Don't Stop Believin'", artist: "Journey", year: 1981, spotifyId: "77NNZQSqzLNqh2A9JhLRkg" },
  { title: "Toy", artist: "Netta", year: 2018, spotifyId: "6VO6JrvcuGMfPOQgT6kSGE" },
  { title: "You Can't Hurry Love", artist: "The Supremes", year: 1966, spotifyId: "1OppEieGNdItZbE14gLBEv" },
  { title: "Dancing Queen", artist: "ABBA", year: 1976, spotifyId: "0GjEhVFGZW8afUYGChu3Rr" },
  { title: "Space Oddity", artist: "David Bowie", year: 1969, spotifyId: "72Z17vmmeQKAg8bptWvpVG" },
  { title: "I Say a Little Prayer", artist: "Aretha Franklin", year: 1968, spotifyId: "3NfxSdJnVdon1axzloJgba" },
  { title: "Timber", artist: "Pitbull", year: 2013, spotifyId: "3cHyrEgdyYRjgJKSOiOtcS" },
];

export const SONGS_BY_GENRE: Record<Genre, SongSeed[]> = {
  international: INTERNATIONAL_SONGS,
  israeli: ISRAELI_SONGS,
};

export const SONG_SEEDS = INTERNATIONAL_SONGS;

export function shuffleDeck(seeds: SongSeed[]): SongSeed[] {
  const arr = [...seeds];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
